site_name: CodeIgniter Tasks
site_description: Documentation for the Tasks library for CodeIgniter 4 framework

theme:
  name: material
  logo: assets/flame.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Raleway
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: codeigniter
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

extra:
  homepage: https://codeigniter.com
  generator: false

  social:
    - icon: material/github
      link: https://github.com/codeigniter4/tasks
      name: GitHub
    - icon: material/twitter
      link: https://twitter.com/CodeIgniterPhp
      name: X
    - icon: material/forum
      link: https://forum.codeigniter.com
      name: Forum Codeigniter
    - icon: material/slack
      link: https://join.slack.com/t/codeigniterchat/shared_invite/zt-244xrrslc-l_I69AJSi5y2a2RVN~xIdQ
      name: Slack


repo_url: https://github.com/codeigniter4/tasks
edit_uri: edit/develop/docs/
copyright: Copyright &copy; 2023 CodeIgniter Foundation.

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - admonition
  - pymdownx.details

extra_css:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.8.0/build/styles/github.min.css
  - assets/css/codeigniter.css
  - assets/css/codeigniter_dark_mode.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.8.0/build/highlight.min.js
  - assets/js/hljs.js

plugins:
  - search

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - CLI Commands: cli-commands.md
  - Basic Usage: basic-usage.md
