# When a PR is opened or a push is made, perform
# a static analysis check on the code using PHPStan.
name: PHPStan

on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'phpstan*'
      - '.github/workflows/analyze.yml'
  push:
    branches:
      - 'develop'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'phpstan*'
      - '.github/workflows/analyze.yml'

jobs:
  build:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer, pecl, phpunit
          extensions: intl, json, mbstring, mysqlnd, xdebug, xml, sqlite3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Create composer cache directory
        run: mkdir -p ${{ steps.composer-cache.outputs.dir }}

      - name: Cache composer dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Create PHPStan cache directory
        run: mkdir -p build/phpstan

      - name: Cache PHPStan results
        uses: actions/cache@v2.1.4
        with:
          path: build/phpstan
          key: ${{ runner.os }}-phpstan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-phpstan-

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Run static analysis
        run: vendor/bin/phpstan analyze
